### ISSUE TITLE
Data link in 3.3 no longer working

### ISSUE THREAD

**Issue by nvitt** [privefl/bigsnpr-extdoc#4]
Hi Florian, 
Thank you for your great R packages, and for creating this helpful documentation. Unfortunately it seems like the example data from Reed et al. (2015) used in "3.3 Exercise: preprocessing" is no longer available at https://www.mtholyoke.edu/courses/afoulkes/Data/statsTeachR/, and I have not been able to find the data elsewhere. Do you maybe have an alternative source for the dataset?
Many thanks, Nicolai

**Comment by privefl** [comment]
I see, the website does not exist anymore..
Fortunately, I have them locally on my computer. I'll upload them and change the tuto.

**Comment by privefl** [comment]
A new link is available.

Thanks for reporting

**Comment by nvitt** [comment]
Thank you
